name: automerge
on:
  push:
#  pull_request:
#    types:
#      - opened
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: add label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.github_token }}
          labels: automerge
          number: "5"
      - name: automerge
        uses: "pascalgn/automerge-action@4775c532c615e0491d53bc42c0893840ae7cc07a"
        env:
          GITHUB_TOKEN: ${{ secrets.MERGE_TOKEN }}
          MERGE_DELETE_BRANCH: true
          MERGE_FILTER_AUTHOR: daviddenton
